version: '3'

services:
  blog-server:
    build: ./php
    image: blog
    depends_on:
      - mysql
      - mysql-test
      - redis
    working_dir: ./blog
    volumes:
      - ./:/application:cached

  horizon:
    build: ./php
    image: blog
    command: php artisan horizon
    depends_on:
      - mysql
    working_dir: ./blog
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
      - MYSQL_DATABASE=blog
    volumes:
      - db-data:/var/lib/mysql:cached

  mysql-test:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - blog-server

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  db-data: